# Generated by Django 6.0.1 on 2026-01-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("button_text", models.CharField(blank=True, max_length=50)),
                ("button_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PressRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("intro", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("signed_by", models.CharField(blank=True, max_length=200)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
                ("highlight", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
