# Generated by Django 6.0.1 on 2026-01-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenshipBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("Eastern Air Tample", "Eastern Air Tample"),
                            ("Western Air Tample", "Western Air Tample"),
                            ("Northern Water Tribe", "Northern Water Tribe"),
                            ("Southern Water Tribe", "Southern Water Tribe"),
                            ("Earth Kingdom", "Earth Kingdom"),
                            ("Fire Nation", "Fire Nation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color1_hex", models.CharField(max_length=7)),
                ("color2_hex", models.CharField(max_length=7)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
