# Generated by Django 6.0.1 on 2026-01-26 20:20

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_citizenshipbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizenshipbadge",
            name="origin",
            field=models.CharField(
                choices=[
                    ("Eastern Air Tample", "Eastern Air Tample"),
                    ("Western Air Tample", "Western Air Tample"),
                    ("Nortern Air Tample", "Nortern Air Tample"),
                    ("Soutern Air Tample", "Soutern Air Tample"),
                    ("Northern Water Tribe", "Northern Water Tribe"),
                    ("Southern Water Tribe", "Southern Water Tribe"),
                    ("Earth Kingdom", "Earth Kingdom"),
                    ("Fire Nation", "Fire Nation"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="citizenshipbadge",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="unique_citizenship_username_ci",
            ),
        ),
    ]
