# Generated by Django 6.0.1 on 2026-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_citizenshipbadge_origin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditableElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("content", models.TextField(blank=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="TabSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("tab_title", models.CharField(max_length=100)),
                ("icon_text", models.CharField(default="N", max_length=2)),
                ("icon_bg_color", models.CharField(default="#2F2F2F", max_length=7)),
                ("icon_text_color", models.CharField(default="#FFFFFF", max_length=7)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
    ]
