# Generated by Django 6.0.1 on 2026-02-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pressrelease_updates"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="citizenshipbadge",
            name="unique_citizenship_username_ci",
        ),
        migrations.DeleteModel(
            name="CitizenshipBadge",
        ),
        migrations.AlterModelOptions(
            name="pressrelease",
            options={"ordering": ["-is_pinned", "-published_at"]},
        ),
    ]
